### ISSUE TITLE
Period (.) in SSID messing things up?

### ISSUE THREAD

**Issue by CT83** [guysoft/HotSpotOS#2]
I had a period `.` in my SSID, and the RPi Zero won't connect to my network. I renamed my network; removed the period, everything is now working. 
Is this somehow related? 
Maybe add this in FAQ?

**Comment by guysoft** [comment]
Hey,
Does this period ssid work in normal Raspbian?

**Comment by CT83** [comment]
Good, question. I will try to run some tests and get back to you.

**Comment by guysoft** [comment]
Closing if no reply

**Comment by CT83** [comment]
Yeah, sure. Didn't really have this problem again
